FROM mysql:8.0.4

ENV MYSQL_DATABASE QueryBuilder
ENV MYSQL_ROOT_PASSWORD noobpasswd
ENV MYSQL_USER simon
ENV MYSQL_PASSWORD noobpasswd

COPY setup.sql /usr/local/bin/setup.sql
COPY setup.sh /docker-entrypoint-initdb.d/setup.sh

EXPOSE 3306

CMD ["mysqld"]