FROM php:8.0.14-fpm-buster

RUN apt-get update \
    && apt-get install -y neovim

COPY installzsh.sh /usr/local/bin/installzsh
RUN chmod +x /usr/local/bin/installzsh \
    && installzsh

RUN mkdir -p /usr/src/app/website
WORKDIR /usr/src/app/website

# Use github token so i can push to the repo without needing to manually add a git remote
ARG GITHUB_TOKEN
RUN git clone "https://${GITHUB_TOKEN}@github.com/simon-instance/QueryBuilder.git" . \
    && git config --global user.email simon@gmail.com \
    && git config --global user.name simon-instance

WORKDIR /usr/src/app/website/src

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN composer install

EXPOSE 9000
EXPOSE 80